# Imagen base de Node.js
FROM node:22.14.0

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar dependencias e instalarlas
COPY ./package.json ./package-lock.json ./
RUN npm install

# Copiar el código fuente
COPY . .

# Construir la aplicación
RUN npm run build

# instalar serve
RUN npm install -g serve

# Exponer el puerto donde correrá React
EXPOSE 3000

# Servir la aplicación con un servidor web ligero
CMD ["serve", "-s", "build"]




