# Imagen base de Node.js
FROM node:22.14.0-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar dependencias e instalarlas
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

# Copiar el código fuente
COPY frontend/ .

# Construir la aplicación
RUN npm run build

# Servir la aplicación con un servidor web ligero
RUN npm install -g serve
CMD ["serve", "-s", "build"]

# Exponer el puerto donde correrá React
EXPOSE 3000