FROM python:3.10

WORKDIR /app

COPY epicgames/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY epicgames/ .

EXPOSE 5010  # Puerto del servicio
CMD ["python", "epicgames.py"]